# __SCENE_TITLE__

This is a self-contained Vite + TypeScript + Three.js project generated by Three.js Scene Factory.

## Run

```bash
npm install
npm run dev
```

Use the mouse to orbit and zoom. Interactive objects highlight on hover. Depending on the Scene Spec, click objects to toggle or open them, drag movable objects along the floor, and use **Reset scene** to restore all initial state.

The source specification is preserved in `scene-spec.json`. Edit that file in the factory and regenerate the project rather than hand-editing generated geometry.
